remote_theme: dieghernan/chulapa
locale                  : es-ES   
title                   : COVID19 en España
timezone                : "Europe/Madrid"
og_image                : "assets/img/header.png"
author:
  name                  :  dieghernan
  location              :  "Madrid, España"
gtag_id                 :  UA-139034853-4
navbar:
  expand: always
  brand:
    title   :  Inicio
  nav:
  - title: Galería
    url: /Galeria
footer:
  links:
    - label: "StackOverflow"
      icon: "fab fa-stack-overflow"
      url:  https://stackoverflow.com/users/7877917/dieghernan
    - label: "GitHub"
      icon: "fab fa-github"
      url: https://github.com/dieghernan/
    - label: "Blog"
      icon: "fas fa-blog"
      url: "https://dieghernan.github.io/"
    - label: "RPubs"
      icon: "fab fa-r-project"
      url: "https://rpubs.com/dieghernan"
googlefonts:
 - url : "https://fonts.googleapis.com/css2?family=Varta&family=Lora&display=swap"
chulapa-skin: 
  autothemer  :  true 
  vars        :    
    primary   :  black
    navbar-chulapa-text-color: white
    font-family-base: "Varta, sans-serif"
    headings-font-family: "Lora, serif"
    navbar-chulapa-toggler-color: "#F5F5F5"
    navbar-chulapa-toggler-border-color: invisible
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      header_type: "base"
      show_sociallinks  : true
  -
    scope:
      path: "assets/png/Casos"
    values:
      image_col         : casos
  -
    scope:
      path: "assets/png/Contagios"
    values:
      image_col         : contagios
  -
    scope:
      path: "assets/png/Fallecidos"
    values:
      image_col         : fallecidos
  -
    scope:
      path: "assets/png/RatioHosp"
    values:
      image_col         : hospitalizados     
compress_html:
  clippings: all
  blanklines: true
plugins:
  - jekyll-github-metadata
  - jekyll-paginate
  - jekyll-include-cache
  - jekyll-sitemap
exclude:
  - README.md
  - Gemfile
  - vendor
  - index.Rmd
  - R/
  - assets/data/
  - LICENSE
  
include:
  - _pages
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  footnote_backlink: '&uarr;'
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
sass:
  sass_dir: _sass
  style: compressed