remote_theme: jekyll/minima
title: COVID19 en España

description: > # this means to ignore newlines until "show_excerpts:"
 Evolución COVID19 en mapas. Creado con R-Studio

minima:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    github:  dieghernan
